# 2. PersistentVolumeClaim (mariadb-pvc.yaml)
# docker-compose의 'volumes: mariadb_db_data'를 대체합니다.
# 'mariadb-db-data'라는 이름의 1GB 디스크 공간을 K8s에 요청합니다.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce # (하나의 노드에서만 읽고 쓸 수 있음, DB에 표준)
  resources:
    requests:
      storage: 1Gi # 1 기가바이트 요청